# =========================
# Builder
# =========================
FROM node:20-bookworm-slim AS builder

WORKDIR /app

RUN apt-get update \
    && apt-get install -y openssl ca-certificates \
    && rm -rf /var/lib/apt/lists/*

ENV PRISMA_CLI_BINARY_TARGETS=linux-arm64-openssl-3.0.x
ENV PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING=1

ENV DATABASE_URL="postgresql://johndoe:mypassword@localhost:5432/mydb?schema=public"

COPY package*.json ./
RUN npm install

COPY . .

RUN npx prisma generate
RUN npm run build


# =========================
# Runtime
# =========================
FROM node:20-bookworm-slim

WORKDIR /app

RUN apt-get update \
    && apt-get install -y openssl ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /app/node_modules && chown -R node:node /app

COPY --chown=node:node package*.json ./

USER node
RUN npm install --omit=dev

COPY --chown=node:node --from=builder /app/dist ./dist
COPY --chown=node:node --from=builder /app/src/generated ./src/generated

CMD ["npm", "run", "start"]
