# =========================
# Builder
# =========================
FROM node:22-bookworm-slim AS builder

WORKDIR /app

RUN apt-get update \
    && apt-get install -y openssl ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Prisma ARM64
ENV PRISMA_CLI_BINARY_TARGETS="native linux-arm64-openssl-3.0.x linux-arm-openssl-3.0.x"
ENV PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING=1

COPY package*.json ./
RUN npm install

COPY . .

RUN npx prisma generate

RUN npm run build


# =========================
# Runtime
# =========================
FROM node:22-bookworm-slim

WORKDIR /app

RUN apt-get update \
    && apt-get install -y openssl ca-certificates \
    && rm -rf /var/lib/apt/lists/*

ENV PRISMA_CLI_BINARY_TARGETS="native linux-arm64-openssl-3.0.x linux-arm-openssl-3.0.x"
ENV PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING=1

# PREPARAR PERMISOS: Crear carpeta y asignar dueño antes de cambiar de usuario
RUN mkdir -p /app/node_modules && chown -R node:node /app

COPY --chown=node:node package*.json ./

USER node
# Ahora node tiene permisos para escribir en /app/node_modules
RUN npm install --omit=dev

COPY --chown=node:node --from=builder /app/prisma.config.ts ./
COPY --chown=node:node --from=builder /app/prisma ./prisma
COPY --chown=node:node --from=builder /app/dist ./dist
COPY --chown=node:node --from=builder /app/src/generated ./src/generated

# El usuario ya es node, no hace falta repetirlo
CMD ["npm", "run", "start"]
