# ---------- BUILD ----------
FROM node:22-slim AS build

WORKDIR /app

COPY package*.json ./

RUN npm install --include=optional

COPY . .
RUN npm run build

# ---------- RUNTIME ----------
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
